Repository Yagnik031/JS-Clock-master, pull requests merged in 2022-10, with the labels that each got.

#1 added Readme file with js file and added config file
  LICENSE
  README.md
  _config.yml
  script.js
Labels: Hacktoberfest, Hacktoberfest-accepted

#3 image added
  329433 black_hair blue bow brown_ha.jpg
Labels: Hacktoberfest, Hacktoberfest-accepted

#4 profile image added
  _Aftershock.png
Labels: Hacktoberfest, Hacktoberfest-accepted

#5 auth gurd added
  auth.guard.ts
  autologin.guard.ts
Labels: Hacktoberfest, Hacktoberfest-accepted

#6 ternary operation task added
  licence.md
  ternary opretor.c
  ternary opretor.exe
Labels: Hacktoberfest, Hacktoberfest-accepted

#7 Home Css File Added
  assets/css/home.module.scss
Labels: Hacktoberfest, Hacktoberfest-accepted

#8 CartItems added
  cartItems.js
Labels: Hacktoberfest, Hacktoberfest-accepted

#9 single & double click directive added
  single-double-click.directive.ts
Labels: enhancement, Hacktoberfest, Hacktoberfest-accepted

#10 ADDED: user management added.
  DeleteUserModal.js
  EditUserForm.js
  Provider.js
  User.js
  UserList.js
  UserProfile.js
Labels: Hacktoberfest, Hacktoberfest-accepted

#11 list.py file added
  index.html
  list.py
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted
